function(regkit_verify_dependency_order)
    set(allowed_targets regkit_compile_settings pcre2_16)

    foreach(target IN LISTS ARGN)
        if (NOT TARGET ${target})
            message(FATAL_ERROR "Unknown RegKit target in dependency order: ${target}")
        endif()

        get_target_property(dependencies ${target} LINK_LIBRARIES)
        if (dependencies STREQUAL "dependencies-NOTFOUND")
            set(dependencies)
        endif()

        foreach(dependency IN LISTS dependencies)
            if (TARGET ${dependency})
                list(FIND allowed_targets ${dependency} dependency_index)
                if (dependency_index EQUAL -1)
                    message(FATAL_ERROR
                        "Invalid RegKit dependency: ${target} -> ${dependency}. "
                        "Dependencies must point to an earlier target.")
                endif()
            endif()
        endforeach()

        list(APPEND allowed_targets ${target})
    endforeach()
endfunction()

function(regkit_verify_include_order)
    file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/src/*.h" "${PROJECT_SOURCE_DIR}/src/*.cpp")
    set(errors)
    foreach(source IN LISTS sources)
        file(RELATIVE_PATH relative "${PROJECT_SOURCE_DIR}/src" "${source}")
        string(REGEX MATCH "^[^/]+" folder "${relative}")
        list(FIND ARGN "${folder}" layer)
        if (layer EQUAL -1)
            continue()
        endif()
        file(STRINGS "${source}" includes REGEX "^#include \"[a-z0-9_]+/")
        foreach(line IN LISTS includes)
            string(REGEX MATCH "\"([a-z0-9_]+)/" match "${line}")
            list(FIND ARGN "${CMAKE_MATCH_1}" included_layer)
            if (included_layer GREATER layer)
                list(APPEND errors "src/${relative}: ${line}")
            endif()
        endforeach()
    endforeach()
    if (errors)
        list(JOIN errors "\n" errors)
        message(FATAL_ERROR "Includes must point to an earlier layer:\n${errors}")
    endif()
endfunction()
